### ISSUE TITLE
Cleaning Finesse Backlog: Removing Irrelevant Issues

### ISSUE THREAD

**Issue by ibrahim-kabir** [ai-cfia/finesse-frontend#105]
## Summary
As part of cleaning up the Finesse backlog, it's crucial to remove issues that are no longer relevant to our project. We've identified several directories that are no longer maintained and contain obsolete issues.

## Tasks
**Archive all unreleavant issues**
- [x] `ailab-db`
- [x] finesse backlog

**Create**
- [ ] Epic: merge Louis with Finesse
- [x] Epic: Research for next Finesse features 
  - [ ] Update the index with new documents or remove some (**daily job?**), Better index in one step, user-friendly 
  - [ ] Feedback on pages for best results from query (thumb up or down)
  - [ ] Expand on document types and sources (RDIMS,PDF,Word,Excel,...)
  - [ ] How to showcase result for non-URL source (Read write to path of the cloud source of the result)
  - [ ] Better highlighting (not keywords but the inferenced search result)
  - [ ] auto-complete (spelling changes results -> offer user default words to improve accuracy)
  - [ ] Filter in query (-keyword)
  - [ ] AutoCorrect the query/word to get improved and accurate results
- [ ] Epic: Better accuracy

**Comment by Francois-Werbrouck** [comment]
Can we rework this issue to it better showcase the priority ranking of the epics and their content

**Comment by k-allagbe** [comment]
I've created either issues or draft issues for the bullet points. Closing this.
