### ISSUE TITLE
Securly manage access to private resources in `Finesse`

### ISSUE THREAD

**Issue by k-allagbe** [ai-cfia/finesse-frontend#108]
Finesse is now moving to allow access to privately managed documents. This involves a number of security steps that need to be implemented from the DevSecOps side. 

From the app development standpoint, we need:
- [ ] A way to display index availability in `finesse-frontend`
- [ ] Public / private indicators in `finesse-frontend`
- [ ] New endpoints in `finesse-backend` for reaching private resources
- [ ] A new private index on top of the private documents
