### ISSUE TITLE
Remove npm version restriction in `finesse-frontend`

### ISSUE THREAD

**Issue by k-allagbe** [ai-cfia/finesse-frontend#116]
## Description
`package.json` specifies:
```json
  "engines": {
    "npm": "^9.8.1",
    "node": "^18.16.0"
  }
```
This was done due to some dependency issues with `create-react-app`. We've now moved to `Vite`, so it is no longer necessary. Also there are major new versions for `npm` and `node`. We need to keep up.

## Tasks
- [ ] Remove the restriction.
- [ ] Ensure the app builds and runs.
- [ ] Ensure tests pass.
- [ ] Update docs if necessary.

## Acceptance Criteria
- `npm 9.8.1` is no longer enforced.
