### ISSUE TITLE
Auto update indexes in `llamaindex-db`

### ISSUE THREAD

**Issue by k-allagbe** [ai-cfia/finesse-frontend#130]
## Description
Currently our indexes are built on static set of documents. We now want a mechanism to auto update the document sets and the indexes.

## Tasks
- [ ] Make an inventory of our indexes, the documents sets they are built on and the source of those documents.
- [ ] Research / Design a mechanism to keep the document sets up to date with their sources or find a way to directly index from sources
- [ ] Auto update indexes

## Acceptance criteria
- Document sets and indexes are consistent with their sources
- Data duplication is minimal
