### ISSUE TITLE
Sometimes reloading the page is necessary to search `finesse-frontend`

### ISSUE THREAD

**Issue by k-allagbe** [ai-cfia/finesse-frontend#132]
## Description
Sometimes, after switching the search engine in the debug panel, searching doesn't seem to work and reloading the page becomes necessary. The exact steps to reproduce are unclear.

## Tasks
- [ ] implement reloading the page on every search (even when the query hasn't changed)
- [ ] find the exact steps to reproduce the issue
- [ ] Investigate and fix
- [ ] update tests

## Acceptance criteria
- The user can perform as many searches as he wants without needing to reload the page
