### ISSUE TITLE
Accessibility update for finesse-frontend

### ISSUE THREAD

**Issue by k-allagbe** [ai-cfia/finesse-frontend#76]
finesse-frontend requires enhancements to meet the accessibility standards as per the "Government of Canada Digital Standards: Playbook." The aim is to improve accessibility for a diverse user base.

## Tasks
- [ ] Review Finesse-Frontend for accessibility compliance.
- [ ] Make necessary updates in the application for improved accessibility.
- [ ] Document standard accessibility practices for the project.
- [ ] Integrate automated accessibility checks.

## Acceptance Criteria
- Finesse-Frontend complies with the necessary accessibility standards.
- Accessibility improvements are evident in the application.
- Standard accessibility practices are documented and implemented.
- Automated accessibility checks are in place and functional.

**Comment by rngadam** [comment]
Note that there are GoC efforts to develop reusable components that have built in usability:

https://github.com/DTS-STN/Service-Canada-Design-System

we should probably also start with automated validation of accessibility of the frontend.

@ThomasCardin  This is the tool https://github.com/18F uses in their Github workflow:

https://github.com/pa11y/pa11y/

used here: 

https://github.com/18F/guides/blob/0e387b07944a1dc68360b92feac5026fbdf68d07/.github/workflows/pull-request.yml#L50
