### ISSUE TITLE
Migrate finesse-frontend from Create-React-App

### ISSUE THREAD

**Issue by k-allagbe** [ai-cfia/finesse-frontend#77]
We currently have finesse-frontend built using `create-react-app` which is now deprecated. As a consequence, vulnerabilities are piling up in the package management. We decided to migrate to `Vite`.

## Tasks
- [ ] Recreate the project with Vite.
- [ ] Update the project's package.json scripts to use Vite commands for development and building.
- [ ] Test the project thoroughly to ensure that it functions correctly after the migration.
- [ ] Update dependencies.
- [ ] Update the project documentation.

Acceptance Criteria:
- finesse-frontend successfully builds and runs using Vite without errors.
- All existing features and functionalities work as expected.
- The project's documentation is updated to include instructions for running and developing the project with Vite.
